Dispatcher:
  qps: 500
  burst: 1000
  contentType: application/vnd.kubernetes.protobuf
Distributor:
  qps: 500
  burst: 1000
  contentType: application/vnd.kubernetes.protobuf
Scheduler:
  qps: 500
  burst: 1000
  contentType: application/vnd.kubernetes.protobuf

